"""Add reaction_type to ForumLike

Revision ID: 1459d14426f2
Revises: 52e44040b280
Create Date: 2025-10-23 11:55:37.156725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1459d14426f2'
down_revision = '52e44040b280'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('forum_likes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reaction_type', sa.String(length=20), nullable=True))
        batch_op.drop_constraint(batch_op.f('uq_user_post_like'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_user_thread_like'), type_='unique')
        batch_op.create_unique_constraint('uq_user_post_reaction', ['user_id', 'post_id', 'reaction_type'])
        batch_op.create_unique_constraint('uq_user_thread_reaction', ['user_id', 'thread_id', 'reaction_type'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('forum_likes', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_thread_reaction', type_='unique')
        batch_op.drop_constraint('uq_user_post_reaction', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_user_thread_like'), ['user_id', 'thread_id'])
        batch_op.create_unique_constraint(batch_op.f('uq_user_post_like'), ['user_id', 'post_id'])
        batch_op.drop_column('reaction_type')

    # ### end Alembic commands ###
