"""Add thread_id to ForumLike

Revision ID: 52e44040b280
Revises: cf286ef388a4
Create Date: 2025-10-23 11:46:55.890915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52e44040b280'
down_revision = 'cf286ef388a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('forum_likes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('thread_id', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint('uq_user_thread_like', ['user_id', 'thread_id'])
        batch_op.create_foreign_key(None, 'forum_threads', ['thread_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('forum_likes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint('uq_user_thread_like', type_='unique')
        batch_op.drop_column('thread_id')

    # ### end Alembic commands ###
