"""Update PrayerRequest and Prayer models

Revision ID: 550e9ce21e36
Revises: cf025ce057dd
Create Date: 2025-09-05 11:34:48.971154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '550e9ce21e36'
down_revision = 'cf025ce057dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prayers', schema=None) as batch_op:
        batch_op.alter_column('message',
               existing_type=sa.TEXT(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prayers', schema=None) as batch_op:
        batch_op.alter_column('message',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###
