"""Add group chats models

Revision ID: 8fc96e0d7629
Revises: a7c8e28543bf
Create Date: 2025-10-09 12:03:36.393000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fc96e0d7629'
down_revision = 'a7c8e28543bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group_chats',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('meta_data', sa.JSON(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('avatar', sa.String(length=500), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('max_members', sa.Integer(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('created_by_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    with op.batch_alter_table('group_chats', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_group_chats_name'), ['name'], unique=False)
        batch_op.create_index('ix_group_chats_public_created', ['is_public', 'created_at'], unique=False)

    op.create_table('group_members',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('meta_data', sa.JSON(), nullable=True),
    sa.Column('group_chat_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('group_role', sa.String(length=20), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("group_role IN ('admin', 'moderator', 'member')", name='ck_group_member_role'),
    sa.ForeignKeyConstraint(['group_chat_id'], ['group_chats.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_chat_id', 'user_id', name='uq_group_member'),
    sa.UniqueConstraint('uuid')
    )
    with op.batch_alter_table('group_members', schema=None) as batch_op:
        batch_op.create_index('ix_group_members_user', ['user_id'], unique=False)

    op.create_table('group_messages',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('meta_data', sa.JSON(), nullable=True),
    sa.Column('group_chat_id', sa.BigInteger(), nullable=False),
    sa.Column('sender_id', sa.BigInteger(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('message_type', sa.String(length=20), nullable=True),
    sa.Column('attachments', sa.JSON(), nullable=True),
    sa.Column('replied_to_id', sa.BigInteger(), nullable=True),
    sa.Column('read_by', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['group_chat_id'], ['group_chats.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['replied_to_id'], ['group_messages.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    with op.batch_alter_table('group_messages', schema=None) as batch_op:
        batch_op.create_index('ix_group_messages_group_created', ['group_chat_id', 'created_at'], unique=False)
        batch_op.create_index('ix_group_messages_sender', ['sender_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('group_messages', schema=None) as batch_op:
        batch_op.drop_index('ix_group_messages_sender')
        batch_op.drop_index('ix_group_messages_group_created')

    op.drop_table('group_messages')
    with op.batch_alter_table('group_members', schema=None) as batch_op:
        batch_op.drop_index('ix_group_members_user')

    op.drop_table('group_members')
    with op.batch_alter_table('group_chats', schema=None) as batch_op:
        batch_op.drop_index('ix_group_chats_public_created')
        batch_op.drop_index(batch_op.f('ix_group_chats_name'))

    op.drop_table('group_chats')
    # ### end Alembic commands ###
