"""Add target_type/target_id to activities

Revision ID: 9a1f5e3c7b2d
Revises: 0c439972a43c
Create Date: 2026-07-11 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a1f5e3c7b2d'
down_revision = '0c439972a43c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('target_type', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('target_id', sa.Integer(), nullable=True))
        batch_op.create_index(
            'ix_activities_target', ['target_type', 'target_id'], unique=False
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.drop_index('ix_activities_target')
        batch_op.drop_column('target_id')
        batch_op.drop_column('target_type')
    # ### end Alembic commands ###
