"""Update PrayerRequest and Prayer models

Revision ID: a7c8e28543bf
Revises: 550e9ce21e36
Create Date: 2025-09-05 12:48:54.647405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7c8e28543bf'
down_revision = '550e9ce21e36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prayer_requests', schema=None) as batch_op:
        batch_op.drop_column('testimony_approved')
        batch_op.drop_column('answered_testimony')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prayer_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('answered_testimony', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('testimony_approved', sa.BOOLEAN(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
