"""Add verses_json to study_plans

Revision ID: cf286ef388a4
Revises: 8fc96e0d7629
Create Date: 2025-10-21 13:17:57.168020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf286ef388a4'
down_revision = '8fc96e0d7629'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test_users')
    op.drop_table('admin_test_model')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
        batch_op.drop_constraint(batch_op.f('notifications_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('study_plans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verses_json', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('study_plans', schema=None) as batch_op:
        batch_op.drop_column('verses_json')

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('notifications_user_id_fkey'), 'users', ['user_id'], ['id'])
        batch_op.alter_column('user_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    op.create_table('admin_test_model',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('admin_test_model_pkey'))
    )
    op.create_table('test_users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('test_users_pkey')),
    sa.UniqueConstraint('email', name=op.f('test_users_email_key')),
    sa.UniqueConstraint('username', name=op.f('test_users_username_key'))
    )
    # ### end Alembic commands ###
