"""Add timeline_post_comments table

Revision ID: ea5c7b9132ee
Revises: f6a2c8e1b3d5
Create Date: 2026-07-15 01:50:57.750582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea5c7b9132ee'
down_revision = 'f6a2c8e1b3d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activities_target'))

    with op.batch_alter_table('forum_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_forum_reports_status'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('forum_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_forum_reports_status'), ['status'], unique=False)

    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activities_target'), ['target_type', 'target_id'], unique=False)

    # ### end Alembic commands ###
