// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzaTbzUc5Y6nhhojlUoiKsO2VujiT-p3k',
    appId: '1:532573763863:web:2a7404e278688d02a2df52',
    messagingSenderId: '532573763863',
    projectId: 'pensaconnect-fa5c3',
    authDomain: 'pensaconnect-fa5c3.firebaseapp.com',
    storageBucket: 'pensaconnect-fa5c3.firebasestorage.app',
    measurementId: 'G-MRMP2CJNVS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYSxVzF9_bFuGun-f90Qgz5kahhag-mQE',
    appId: '1:532573763863:android:792e32dbef43cc3ba2df52',
    messagingSenderId: '532573763863',
    projectId: 'pensaconnect-fa5c3',
    storageBucket: 'pensaconnect-fa5c3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7k-LFDcm9WjHXD3qSd_EIj5hN-HEki1M',
    appId: '1:532573763863:ios:574a239832a5ef3ca2df52',
    messagingSenderId: '532573763863',
    projectId: 'pensaconnect-fa5c3',
    storageBucket: 'pensaconnect-fa5c3.firebasestorage.app',
    iosBundleId: 'com.yourchurch.pensaconnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7k-LFDcm9WjHXD3qSd_EIj5hN-HEki1M',
    appId: '1:532573763863:ios:574a239832a5ef3ca2df52',
    messagingSenderId: '532573763863',
    projectId: 'pensaconnect-fa5c3',
    storageBucket: 'pensaconnect-fa5c3.firebasestorage.app',
    iosBundleId: 'com.yourchurch.pensaconnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAzaTbzUc5Y6nhhojlUoiKsO2VujiT-p3k',
    appId: '1:532573763863:web:f4c30c9a6d4fbfb3a2df52',
    messagingSenderId: '532573763863',
    projectId: 'pensaconnect-fa5c3',
    authDomain: 'pensaconnect-fa5c3.firebaseapp.com',
    storageBucket: 'pensaconnect-fa5c3.firebasestorage.app',
    measurementId: 'G-PNESPTN7PD',
  );
}
